name: CD ECS
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      tag:
        required: true
        type: string
      repository:
        required: true
        type: string
      open:
        required: true
        type: boolean
        default: true
      labels:
        required: true
        type: string
      ref:
        required: true
        type: string
      environment:
        description: "Environment name"
        type: string
        required: true
      spacelift-organization:
        description: "Spacelift organization"
        type: string
        required: true
    secrets:
      secret-outputs-passphrase:
        description: "Passphrase for secret outputs"
        required: true
      github-private-actions-pat:
        required: true
      spacelift-api-key-id:
        required: true
      spacelift-api-key-secret:
        required: true

permissions:
  pull-requests: write
  deployments: write
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ["self-hosted"]
    environment:
      name: dev
      url: ${{ steps.deploy.outputs.webapp-url }}
    steps:
      - uses: cloudposse/github-action-secret-outputs@0.1.0
        id: image
        with:
          secret: ${{ secrets.secret-outputs-passphrase }}
          op: decode
          in: ${{ inputs.image }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Environment Info
        uses: cloudposse/github-action-interface-environment@0.1.0
        id: environment
        with:
          implementation_repository: cloudposse/actions-private
          implementation_path: 'ecs-environments'
          implementation_ref: main
          implementation_github_pat: ${{ secrets.github-private-actions-pat }}
          environment: ${{ inputs.environment }}
          namespace: ${{ inputs.repository }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: ${{ steps.environment.outputs.region }}
          role-to-assume: ${{ steps.environment.outputs.cluster-role }}
          role-skip-session-tagging: true

      - name: Deploy
        uses: cloudposse/github-action-deploy-ecs@init
        id: deploy
        with:
          stack: ${{ steps.environment.outputs.cluster }}
          ssm-path: ${{ steps.environment.outputs.namespace }}
          namespace: ${{ steps.environment.outputs.namespace }}
          image: ${{ steps.image.outputs.out }}
          image-tag: ${{ inputs.tag }}
          operation: deploy
          debug: false
          github_token: ${{ secrets.github-private-actions-pat }}
          organization: ${{ inputs.spacelift-organization }}
          api_key_id: ${{ secrets.spacelift-api-key-id }}
          api_key_secret: ${{ secrets.spacelift-api-key-secret }}
