name: CD Helmfile
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      tag:
        required: true
        type: string
      repository:
        required: true
        type: string
      environment:
        description: "Environment name"
        type: string
        required: true
    secrets:
      secret-outputs-passphrase:
        description: "Passphrase for secret outputs"
        required: true
      github-private-actions-pat:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy.outputs.webapp-url }}
    steps:
      - uses: cloudposse/github-action-secret-outputs@0.1.0
        id: image
        with:
          secret: ${{ secrets.secret-outputs-passphrase }}
          op: decode
          in: ${{ inputs.image }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Environment Info
        uses: cloudposse/github-action-interface-environment@0.2.0
        id: environment
        with:
          implementation_repository: cloudposse/actions-private
          implementation_path: 'environments/'
          implementation_ref: main
          implementation_github_pat: ${{ secrets.github-private-actions-pat }}
          environment: ${{ inputs.environment }}
          namespace: ${{ inputs.environment }}
          repository: ${{ inputs.repository }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-region: ${{ steps.environment.outputs.region }}
          role-to-assume: ${{ steps.environment.outputs.cluster-role }}
          role-skip-session-tagging: true

      - name: Deploy
        uses: cloudposse/github-action-deploy-helmfile@0.2.0
        id: deploy
        with:
          aws-region: ${{ steps.environment.outputs.region }}
          cluster: ${{ steps.environment.outputs.cluster }}
          environment: ${{ steps.environment.outputs.name }}
          namespace: ${{ steps.environment.outputs.namespace }}
          image: ${{ steps.image.outputs.out }}
          image-tag: ${{ inputs.tag }}
          operation: deploy
