name: |-
  CI - Codeowners
  
  Validate CODEOWNERS and suggest changes
  
  ### Usage 
  ```yaml
    name: Validate CODEOWNERS
    on:
      workflow_call:
      
    jobs:
      cd:
        uses: cloudposse/github-actions-workflows/.github/workflows/ci-codeowners-full.yml@main
  ```
on:
  workflow_call:
    inputs:
      runs-on:
        description: "Overrides job runs-on setting (json-formatted list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'
    secrets:
      github_access_token:
        description: "GitHub API token"
        required: false

jobs:
  validate-codeowners:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: mszostok/codeowners-validator@v0.7.4
        # Main branch / Pull request from the same repo
        name: "Validate CODEOWNERS"
        with:
          # For now, remove "files" check to allow CODEOWNERS to specify non-existent
          # files so we can use the same CODEOWNERS file for Terraform and non-Terraform repos
          #   checks: "files,syntax,owners,duppatterns"
          checks: "syntax,duppatterns,owners"
          owner_checker_allow_unowned_patterns: "false"
          # Admin GitHub access token is required only if the `owners` check is enabled
          github_access_token: "${{ secrets.github_access_token }}"
