name: |-
  CI - Readme
  
  Validate README.yaml, README.md and suggest changes
  
  ### Usage 
  ```yaml
    name: Validate Readme
    on:
      workflow_call:
    
    permissions:
      pull-requests: write
      id-token: write
      contents: read
      
    jobs:
      ci-readme:
        uses: cloudposse/github-actions-workflows/.github/workflows/ci-readme.yml@main
        with:
          suggestions: true
          filter-mode: diff_context
  ```
on:
  workflow_call:
    inputs:
      suggestions:
        description: "Enable Reviewdog suggestions (pull request only)"
        type: boolean
        required: true
      filter-mode:
        description: "Reviewdog filter mode"
        type: string
        required: true
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'

jobs:
  validate:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate readme
        shell: bash
        run: |
          make init
          make readme/build

      - name: Check readme
        id: readme_diff
        shell: bash
        run: git diff --exit-code
        continue-on-error: true

      - name: Auto-commit readme for bot pull requests
        id: auto_commit
        if: | 
          steps.readme_diff.outcome == 'failure' && 
          startsWith(github.ref_name, 'renovate/') &&
          inputs.suggestions
        run: |
          git commit -m "Update README.md" -a
          git push 

      - name: Status check
        shell: bash
        run: | 
          git diff --exit-code && success="true" || success="false"
          if [ "$success" = "false" ]; then
            echo "README.md is outdated. Please run the following commands locally and push the file:"
            echo "  make init"
            echo "  make readme"
            exit 1
          fi
