name: |-
  CI - Readme
  
  Validate README.yaml, README.md and suggest changes
  
  ### Usage 
  ```yaml
    name: Validate Readme
    on:
      workflow_call:
    
    permissions:
      pull-requests: write
      id-token: write
      contents: read
      
    jobs:
      ci-readme:
        uses: cloudposse/github-actions-workflows/.github/workflows/ci-readme.yml@main
        with:
          suggestions: true
          filter-mode: diff_context
  ```
on:
  workflow_call:
    inputs:
      suggestions:
        description: "Enable Reviewdog suggestions (pull request only)"
        type: boolean
        required: true
      filter-mode:
        description: "Reviewdog filter mode"
        type: string
        required: true
      ref:
        description: "Checkout ref"
        type: string
        required: false
        default: ${{ github.ref_name }}
      repository:
        description: "Checkout repository"
        type: string
        required: false
        default: ${{ github.repository }}
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'

jobs:
  validate:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    environment: release
    steps:
      - uses: actions/create-github-app-token@v1
        id: github-app
        with:
          app-id: ${{ vars.BOT_GITHUB_APP_ID }}
          private-key: ${{ secrets.BOT_GITHUB_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
          fetch-depth: 0
          token: ${{ steps.github-app.outputs.token }}

      - uses: cloudposse-github-actions/readme@0.3.0
        with:
          token: ${{ steps.github-app.outputs.token }}
          readme_enabled: true
          banner_enabled: true
          validate_readme: true
          commit_method: 'commit'
          commit_push_options: '--force-with-lease'
