name: |-
  CI - Readme
  
  Auto-generate Readme.md
  
  ### Usage 
  ```yaml
    name: Generate Readme
    on:
      workflow_call:
    
    permissions:
      pull-requests: write
      id-token: write
      contents: read
      
    jobs:
      cd:
        uses: cloudposse/github-actions-workflows/.github/workflows/ci-readme.yml@main
        with:
          suggestions: true
  ```
on:
  workflow_call:
    inputs:
      suggestions:
        description: "Enable Reviewdog suggestions (pull request only)"
        type: boolean
        required: true
      runs-on:
        description: "Overrides job runs-on setting"
        type: string
        required: false
        default: ubuntu-latest

jobs:
  update-readme:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate readme
        shell: bash
        run: |
          make init
          make readme/build

      - name: Reviewdog suggester
        if: ${{ inputs.suggestions }}
        uses: cloudposse/action-suggester@master
        with:
          tool_name: "make init readme/build"
          cleanup: false
          # Will not work under diff_context bc readme.yaml generates readme.md
          filter_mode: nofilter

      - name: Status check
        shell: bash
        run: git diff --exit-code
