name: |-
  CI - Terraform
  
  Lint, format and validate terraform code
  
  ### Usage 
  ```yaml
    name: Terraform ChatOps
    on:
      workflow_call:
    
    permissions:
      pull-requests: write
      id-token: write
      contents: read
  
    jobs:
      cd:
        uses: cloudposse/github-actions-workflows/.github/workflows/ci-chatops.yml@main
        with:
          suggestions: true
  ```
on:
  workflow_call:
    inputs:
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'

jobs:
  terraform-test:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: cloudposse/actions/github/slash-command-dispatch@0.33.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: cloudposse/actions
          commands: terraform-test
          permission: triage
          issue-type: pull-request
          reactions: false
