name: Complex workflow - Feature branch
on:
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
      repository:
        required: true
        type: string
      registry:
        description: "Docker registry"
        required: false
        type: string
        default: registry.hub.docker.com
      open:
        required: true
        type: boolean
        default: true
      labels:
        required: true
        type: string
      ref:
        required: true
        type: string
    secrets:
      github-private-actions-pat:
        required: true

permissions:
  pull-requests: write
  deployments: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Preview deployments controller
        uses: cloudposse/github-action-preview-environment-controller@0.9.0
        id: controller
        with:
          labels: ${{ inputs.labels }}
          open: ${{ inputs.open }}
          env-label: |
            preview: deploy
            qa1: deploy/qa1
            qa2: deploy/qa2
            qa3: deploy/qa3
            qa4: deploy/qa4

    outputs:
      namespace: ${{ inputs.ref }}
      labels_env: ${{ steps.controller.outputs.labels_env }}
      deploy_envs: ${{ steps.controller.outputs.deploy_envs }}
      destroy_envs: ${{ steps.controller.outputs.destroy_envs }}

  build:
    runs-on: ["self-hosted"]
    if: ${{ inputs.open }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        id: build
        uses: cloudposse/github-action-docker-build-push@0.1.0
        with:
          organization: ${{ inputs.organization }}
          repository: ${{ inputs.repository }}
          registry: ${{ inputs.registry }}

    outputs:
      image: ${{ steps.build.outputs.image }}
      tag: ${{ steps.build.outputs.tag }}

  deploy:
    runs-on: ["self-hosted"]
    if: ${{ needs.context.outputs.deploy_envs != '[]'  }}
    strategy:
      matrix:
        env: ${{ fromJson(needs.context.outputs.deploy_envs) }}
    environment:
      name: ${{ matrix.env }}
      url: ${{ steps.deploy.outputs.webapp-url }}
    needs: [ context, build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Environment Info
        uses: cloudposse/github-action-interface-environment@0.1.0
        id: environment
        with:
          implementation_repository: cloudposse/actions-private
          implementation_path: 'environments/'
          implementation_ref: main
          implementation_github_pat: ${{ secrets.github-private-actions-pat }}
          environment: ${{ matrix.env }}
          namespace: ${{ needs.context.outputs.namespace }}

      - name: Deploy
        uses: cloudposse/github-action-deploy-helmfile@0.1.0
        id: deploy
        with:
          aws-region: ${{ steps.environment.outputs.region }}
          base-role: ${{ steps.environment.outputs.role }}
          cluster: ${{ steps.environment.outputs.cluster }}
          cluster-role: ${{ steps.environment.outputs.cluster-role }}
          environment: ${{ steps.environment.outputs.name }}
          namespace: ${{ steps.environment.outputs.namespace }}
          image: ${{ needs.build.outputs.image }}
          image-tag: ${{ needs.build.outputs.tag }}
          operation: deploy

  destroy:
    runs-on: ["self-hosted"]
    if: ${{ needs.context.outputs.destroy_envs != '[]'  }}
    strategy:
      matrix:
        env: ${{ fromJson(needs.context.outputs.destroy_envs) }}
    permissions:
      pull-requests: write
      deployments: write
    needs: [ context ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Seek deployment
        uses: cloudposse/github-action-seek-deployment@0.1.0
        id: deployment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ matrix.env }}
          ref: ${{ inputs.ref }}
          status: success

      - name: Environment Info
        uses: cloudposse/github-action-interface-environment@0.1.0
        if: ${{ steps.deployment.outputs.id != '' }}
        id: environment
        with:
          implementation_repository: cloudposse/actions-private
          implementation_path: 'environments/'
          implementation_ref: main
          implementation_github_pat: ${{ secrets.github-private-actions-pat }}
          environment: ${{ matrix.env }}
          namespace: ${{ needs.context.outputs.namespace }}

      - name: Destroy
        uses: cloudposse/github-action-deploy-helmfile@0.1.0
        if: ${{ steps.deployment.outputs.id != '' }}
        id: deploy
        with:
          aws-region: ${{ steps.environment.outputs.region }}
          base-role: ${{ steps.environment.outputs.role }}
          cluster: ${{ steps.environment.outputs.cluster }}
          cluster-role: ${{ steps.environment.outputs.cluster-role }}
          environment: ${{ steps.environment.outputs.name }}
          namespace: ${{ steps.environment.outputs.namespace }}
          image: "<none>"
          image-tag: "<none>"
          operation: destroy

      - name: Inactivate deployment
        uses: chrnorm/deployment-status@v2.0.0
        if: ${{ steps.deployment.outputs.id != '' }}
        with:
          state: inactive
          token: ${{ github.token }}
          deployment-id: ${{ steps.deployment.outputs.id }}

      - name: Cleanup label
        uses: cloudposse/github-action-preview-labels-cleanup@0.1.0
        if: ${{ ! inputs.open }}
        with:
          labels_env: ${{ needs.context.outputs.labels_env }}
          env: ${{ matrix.env }}
