name: |-
  Controller - Atmos affected stacks
  
  Get stacks affected in the commit

  ### Usage 

  ```yaml
    name: Stacks affected
    on:
      push:
        branches: [ main ]
  
    jobs:
      do:
        uses:  cloudposse/github-actions-workflows/.github/workflows/controller-atmos-affected-stacks.yml@main
  ```

on:
  workflow_call:
    inputs:
      dir:
        description: Directory with applications
        required: true
        type: string
    outputs:
      stacks:
        description: "Affected stacks"
        value: ${{ jobs.get-affected-property-stacks.outputs.matrix }}
      has-affected-stacks:
        description: "Has affected stacks"
        value: ${{ jobs.get-affected-property-stacks.outputs.has-affected-stacks }}

jobs:
  get-affected-property-stacks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      has-affected-stacks: ${{ steps.matrix.outputs.matrix!='{"include":[]}'}}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: cloudposse/github-action-setup-atmos@v1.0.0
      - id: affected
        uses: cloudposse/github-action-atmos-affected-stacks@0.0.1
        with:
          install-atmos: false
          install-terraform: false
      - id: matrix
        run: |
          matrix=$(echo ${{ steps.affected.outputs.affected }} | jq -c '{include:[.[]]}')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
