name: |-
  Controller - Release
  
  Create a github release

  ### Usage 

  ```yaml
    name: Draft release
    on:
      push:
        branches: [ main ]

    jobs:
      do:
        uses:  cloudposse/github-actions-workflows/.github/workflows/controller-release.yml@main

  ```

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        with:
          prerelease: false
          config-name: auto-release.yml
