name: |-
  Controller - Release
  
  Create a github release

  ### Usage 

  ```yaml
    name: Draft release
    on:
      workflow_call:

    jobs:
      do:
        uses:  cloudposse/github-actions-workflows/.github/workflows/controller-release.yml@main

  ```

on:
  workflow_call:
    inputs:
      ref:
        description: "The release target, i.e. branch or commit it should point to"
        required: false
        default: ${{ github.sha }}
        type: string
      runs-on:
        description: "Overrides job runs-on setting"
        type: string  # json
        required: false
        default: '"ubuntu-latest"'

jobs:
  release:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Get PR from merged commit to master
      - uses: actions-ecosystem/action-get-merged-pull-request@v1
        id: get-merged-pull-request

      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        with:
          publish: ${{ !contains(steps.get-merged-pull-request.outputs.labels, 'no-release') }}
          prerelease: false
          config-name: auto-release.yml