name: |-
  Controller - Atmos affected stacks
  
  Get stacks affected in the commit

  ### Usage 

  ```yaml
    name: Stacks affected
    on:
      push:
        branches: [ main ]
  
    jobs:
      do:
        uses:  cloudposse/github-actions-workflows/.github/workflows/controller-atmos-affected-stacks.yml@main
  ```

on:
  workflow_call:
    inputs:
      stacks:
        description: Stacks
        required: false
        type: string

jobs:
  get-affected-property-stacks:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "matrix=test" >> $GITHUB_OUTPUT
