name: Dockerized Appication - Main branch
on:
  workflow_call:
    inputs:
      organization:
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      secret-outputs-passphrase:
        description: "Passphrase for secret outputs"
        required: true
      registry:
        description: "Docker registry"
        required: true
      github-private-actions-pat:
        required: true
      ecr-region:
        required: true
        description: "AWS region for ECR"
      ecr-iam-role:
        required: true
        description: "IAM for ECR"

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-dockerized-app-build.yml@main
    with:
      organization: ${{ inputs.organization }}
      repository: ${{ inputs.repository }}
    secrets:
      ecr-region: ${{ secrets.ecr-region }}
      ecr-iam-role: ${{ secrets.ecr-iam-role }}
      registry: ${{ secrets.registry }}
      secret-outputs-passphrase: ${{ secrets.secret-outputs-passphrase }}

  cd:
    uses: cloudposse/github-actions-workflows/.github/workflows/cd-helmfile.yml@main
    needs: [ ci ]
    with:
      image: ${{ needs.ci.outputs.image }}
      tag: ${{ needs.ci.outputs.tag }}
      repository: ${{ inputs.repository }}
      environment: dev
    secrets:
      secret-outputs-passphrase: ${{ secrets.secret-outputs-passphrase }}
      github-private-actions-pat: ${{ secrets.github-private-actions-pat }}

  draft_release:
    name: draft release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [ deploy ]
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Create/Update Draft release
        uses: release-drafter/release-drafter@v5
        with:
          publish: false
          prerelease: false
          config-name: configs/draft-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

