name: |-
  Scheduled Readme
  
  Scheduled update of readme.md
  
  ### Usage 
  ```yaml
    name: scheduled-readme
    on:
      workflow_call:
    
    permissions:
      pull-requests: write
      id-token: write
      contents: read
      
    jobs:
      scheduled-readme:
        uses: cloudposse/github-actions-workflows/.github/workflows/scheduled-readme.yml@main
  ```
on:
  workflow_call:
    inputs:
      base-branch:
        description: "Repo default branch"
        type: string
        required: false
        default: 'main'
      runs-on:
        description: "Overrides job runs-on setting (json-encoded list)"
        type: string
        required: false
        default: '["ubuntu-latest"]'

jobs:
  ci-readme:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-readme.yml@main
    with:
      runs-on: ${{ inputs.runs-on }}
    secrets: inherit      
